url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

title: Intelligent Systems Laboratory
email: raktim@tamu.edu
description: > # this means to ignore newlines until "baseurl:"
  Intelligent Systems Laboratory
baseurl: "" # the subpath of your site, e.g. /blog
url: "isrlab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
# theme: minima

include: ['_pages']
